/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package example.kotlin

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun `App Has A Greeting`() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting)
    }
}
